# cluster_config.yml - cluster configuration
__default__:
  account: sansam-lab
  partition: serial
  time: 08:00:00
  cpus-per-task: 2
  mem: 16G
  output: results/logs/slurm-%x.%A.%a.log

trim_reads_with_fastp:
  cpus-per-task: 8
  mem: 64G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

align_reads_with_bwamem:
  cpus-per-task: 12
  mem: 96G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

align_stats_gen_sam:
  cpus-per-task: 2
  mem: 16G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

call_peaks_with_macs2:
  cpus-per-task: 12
  mem: 96G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

make_bigwig:
  cpus-per-task: 8
  mem: 64G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

bin_processing:
  cpus-per-task: 8
  mem: 64G
  time: 10:00:00
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

sigma_analysis:
  cpus-per-task: 4
  mem: 32G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err

create_bedgraphs:
  cpus-per-task: 2
  mem: 16G
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.log
  error: results/logs/{rule}.{wildcards.sample}.err
